# Server
server.port=8080

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=emailConsumerGroup
spring.kafka.topic.name=sendEmail
spring.kafka.producer.properties.allow.auto.create.topics=true

# Gmail SMTP - Port 465 SSL
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=shekharshadulhak011@gmail.com
spring.mail.password=rfmriihwusnzrbig


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Logging
logging.level.root=INFO
logging.level.com.emailservice=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.org.springframework.mail=DEBUG
logging.level.org.apache.kafka.clients=ERROR

